version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: tele_postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    container_name: tele_adminer
    ports:
    - 8090:8080
